### PR TITLE
fix: Fixing valueLocale and consolidating APIs

### PR DESCRIPTION
**Pull request by Golodhros**
## Description
Renames locale to valueLocale when suitable 
Updates numberFormat documentation
Implements locale in stacked bar chart

## Motivation and Context
Fixes https://github.com/britecharts/britecharts/issues/773
Part of https://github.com/britecharts/britecharts/projects/2

## How Has This Been Tested?
Updates tests
Checked on sandbox 

## Types of changes

-   [ ] Refactor (changes the way we code something without changing its functionality)
-   [x] Bug fix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

-   [ ] Latest master code has been merged into this branch
-   [ ] No commented out code (if required, place // TODO above with explanation)
-   [ ] No linting issues
-   [ ] Build is successful
-   [ ] Code follows the [API Guidelines](http://britecharts.github.io/britecharts/topics-index.html#toc5__anchor)
-   [ ] Updated the documentation
-   [ ] Added tests to cover changes
-   [ ] All new and existing tests passed

### CODE REVIEW

**Comment by Golodhros** [comment]
@maikdiepenbroek I think this will solve most of the issues.

I opted to keep .locale for the date locales, as it seems common and now that the documentation is not mixed up and has examples it should be OK.

**Review by DalerAsrorov — APPROVED** [review]

**Comment by maikdiepenbroek** [comment]
@Golodhros Perfect, thank you so much for all the effort. I was working on the the functionality but there was only so much i could do each day so progress was slow. So thanks again.

**Comment by Golodhros** [comment]
Happy to help @maikdiepenbroek !
We still have one bug related to date formats: https://github.com/britecharts/britecharts/issues/681 in case you want to take a look at it!

**Comment by maikdiepenbroek** [comment]
Sure, i'll have a look at it. Maybe i can help!

**Pull request merged**
