### PR TITLE
feat: smoother animation for mini-tooltip

### PR DESCRIPTION
**Pull request by ImADrafter**
## Description

Make the mini-tooltip animation smoother.

## Motivation and Context

Related issue: 
https://github.com/britecharts/britecharts/issues/108
Im not sure if I am handling opacity correctly, since the tooltip is already being styled with 'visibility' and probably we should get rid of that attr. What do you think ? Im looking foward for suggestions.

## Screenshots (if appropriate):

Previously, the mini-tooltip was showing like this:
[

](url)

I tried to make it smoother, like this:

## Types of changes

-   [ ] Refactor (changes the way we code something without changing its functionality)
-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

-   [x] Latest master code has been merged into this branch
-   [X] No commented out code (if required, place // TODO above with explanation)
-   [x] No linting issues
-   [x] Build is successful
-   [x] Code follows the [API Guidelines](http://britecharts.github.io/britecharts/topics-index.html#toc5__anchor)
-   [ ] Updated the documentation
-   [ ] Added tests to cover changes
-   [x] All new and existing tests passed

### CODE REVIEW

**Comment by Golodhros** [comment]
Hi @ImADrafter, thanks a lot for this contribution! This is awesome!

Next time, you might want to open a ticket first, I wouldn't want to disappoint you if your PR won't get merged.

**Review by Golodhros — APPROVED** [review]
LGTM

**Comment by Golodhros** [comment]
This should be available in the version 2.17.2 pretty soon!

**Comment by ImADrafter** [comment]
> Hi @ImADrafter, thanks a lot for this contribution! This is awesome!
> 
> Next time, you might want to open a ticket first, I wouldn't want to disappoint you if your PR won't get merged.

Hmm, so, the [related issue](https://github.com/britecharts/britecharts/issues/108) is not beign closed ? I thought It wasn't necessary to open a new ticket :P 

TY!

**Comment by Golodhros** [comment]
Oh, my bad! 
I didn't remember about this one.

Thanks again!!

**Pull request merged**
