### PR TITLE
fix: 861 line chart - set a minimal y axis range

### PR DESCRIPTION
**Pull request by shayh**
resolve https://github.com/britecharts/britecharts/issues/861

### CODE REVIEW

**Comment by Golodhros** [comment]
Hi @shayh, thanks for your contribution!

**Comment by Golodhros** [comment]
Version 2.17.1 should be available soon with the fix!

**Comment by Golodhros** [comment]
@all-contributors please add @shayh for code

**Comment by shayh** [comment]
awesome, thanks!

**Pull request merged**
