### PR TITLE
Add yAxisTickFormat export

### PR DESCRIPTION
**Pull request by Lennen**
Possibility to export yAxisTickFormat and redefine its value.

## Description

The long numbers like "10000000" are shown in exponential form like "1e+7". There needs a possibility to choose the format you want, for instance, "10000000".

## Motivation and Context

Some persons who are using charts on our web-application, do not know how to use exponential data format. For this case, it is important simply to change the exponential format to another one. 
When I searched for an issue, I found that there is a possibility to change numbers format, but not for any chart type: https://github.com/eventbrite/britecharts/issues/757 For instance, it should be possible to change numbers format of the Bar Chart, but not of the Step Chart. 

## How Has This Been Tested?

When I added this code  I proposed to the library file step.min.js, I could edit y label numbers format using the property yAxisTickFormat. 

## Types of changes

- [ ] Refactor (changes the way we code something without changing its functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [+] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] Latest master code has been merged into this branch
- [+] No commented out code (if required, place // TODO above with explanation)
- [ ] No linting issues
- [+ ] Build is successful
- [ ] Code follows the [API Guidelines](http://eventbrite.github.io/britecharts/topics-index.html#toc5__anchor)
- [ ] Updated the documentation
- [ ] Added tests to cover changes
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by DalerAsrorov** [comment]
Please do not make PRs unless there is an issue related to it. Create an issue first or find a reference to it. The function lacks comments and tests as well.

**Comment by Golodhros** [comment]
Hi @Lennen,

Thanks for the PR, however, as Daler mentioning, it is usually better to ask first. In this case, we were thinking of deprecating the Step chart in the next version of Britecharts, so maybe it was not a great use of your time.

That said, if you really need this right now, I am OK to add this feature, given that you add the missing tests and comments.

Thanks!

**Comment by Lennen** [comment]
Hello,
thanks. It is interesting. When the Step chart will be deprecated? It is interesting to know the aproximal data of next release.
In our web-application, I'm using your Britecharts to create different representation of user's data. So that, user has many tables with some activity during the day, month, year... And I would like to get to him instruments to visualize these data the best way he want. If there will be no Step Chart, it will be less possibilities. But I found that there is a problem with great numbers - the representation of great numbers is exponential, while I want to use 1xxx,xxx,xxx format. I fixed many problems before - with long text overlaying on the x-axis etc, but here there is no beautiful possibility to fix without library modification.

So, you'd like to say you will make a new feature instead of Step Chart or will rewrite the code? Just for me it is critical to know about how it will be better to fix the problem with the numbers format changing. 
Anyway, maybe Yes, it should be good for now to put my fix, if there is no issue now and if the release of the next version will be not during next couple of weeks, because of I want the beautiful representation of the data now in our application.
Sincerely, Eugene N. Rychkov     On Friday, 21 February 2020, 22:15:51 GMT+3, Marcos Iglesias <notifications@github.com> wrote:  
 
 
Hi @Lennen,

Thanks for the PR, however, as Daler mentioning, it is usually better to ask first. In this case, we were thinking of deprecating the Step chart in the next version of Britecharts, so maybe it was not a great use of your time.

That said, if you really need this right now, I am OK to add this feature, given that you add the missing tests and comments.

Thanks!

**Comment by Golodhros** [comment]
Hi @Lennen,

I am not sure when we will have ready the version 3. I can tell you that it won't be ready in at least one month.

As mentioned before, I am OK to add your fix, but you would still need to provide the missing tests and comments. You can look at the rest of the file and its tests to see how to create these.

**Comment by Lennen** [comment]
ok.    On Tuesday, 25 February 2020, 07:15:10 GMT+3, Marcos Iglesias <notifications@github.com> wrote:  
 
 
Hi @Lennen,

I am not sure when we will have ready the version 3. I can tell you that it won't be ready in at least one month.

As mentioned before, I am OK to add your fix, but you would still need to provide the missing tests and comments. You can look at the rest of the file and its tests to see how to create these.

**Comment by Lennen** [comment]
I've done it.

**Comment by Golodhros** [comment]
Sorry @Lennen, maybe you forgot to push the update to your branch?

**Comment by miglesiasEB** [comment]
Hi @Lennen , could you try that again?

**Pull request closed without merging**
